name: 'cmake'
description: 'run cmake configure and build'
inputs:
  source-dir:
    description: 'Source Directory'
    required: 'true'
    default: ''
  build-dir:
    description: 'Build Directory'
    required: 'true'
    default: ''
  build-type:
    description: 'cmake build type'
    required: 'true'
    default: 'Debug'
    
runs:
  using: "composite"
  steps:
  - name: Create Build Environment
    shell: bash
    run: cmake -E make_directory "${{inputs.build-dir}}"

  - name: Configure CMake
    shell: bash
    working-directory: ${{inputs.build-dir}}
    run: cmake 
        -S "${{inputs.source-dir}}" 
        -B "${{inputs.build-dir}}" 
        -DCMAKE_BUILD_TYPE=${{inputs.build-type}}         
        -DSMTG_ENABLE_VSTGUI_SUPPORT=ON
        -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF
        -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF
        -DGITHUB_ACTIONS=ON

  - name: Build
    shell: bash
    working-directory: ${{inputs.build-dir}}
