name: macOS Build

on: 
  workflow_dispatch: 

env:
  build-dir: build
  build-type: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]

    steps:
    - name: Base plugin Repo checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: VSTSDK Repo checkout
      uses: actions/checkout@v4
      with:
        repository: Kiriki-liszt/vst3sdk
        ref: 'v3.7.9_mod'
        path: "./vst3sdk" 
        submodules: 'recursive'

    - name: Install Dependencies
      run: sudo apt-get install libx11-xcb-dev libxcb-util-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Build
      uses: ./.github/actions/cmake
      with:
        source-dir: '${{github.workspace}}'
        build-dir: '${{github.workspace}}/${{env.build-dir}}'
        build-type: '${{env.build-type}}'
        
    - name: Upload VST
      uses: actions/upload-artifact@v4
      with:
        name: VST-artifact
        path: build/VST3
